# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/jammy64"

 config.vm.network "public_network", bridge: ["enp3s0"]

 # shared data
 config.vm.synced_folder "./s_data", "/vagrant_data"

 config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
 
    # Customize the amount of memory on the VM:
    vb.memory = "8192"
    vb.cpus   = 8
  end

  config.vm.provision "tools-0", type: "shell",
    path: "https://raw.githubusercontent.com/simplyatul/vagrant-vms/main/tools-0-install.sh"

  config.vm.provision "docker" do |d|
  end

  config.vm.provision "setaliases", type:"shell", inline: <<-SHELL
    curl -LO "https://raw.githubusercontent.com/simplyatul/bin/master/setaliases.sh"
    # following line not working...ToDo - Debug
    echo "source ~/setaliases.sh" >> ~/.bashrc
  SHELL

  config.vm.provision "kubectl", type:"shell",
    path: "https://raw.githubusercontent.com/simplyatul/vagrant-vms/main/kubectl-install.sh"

  config.vm.provision "kind", type:"shell",
    path: "https://raw.githubusercontent.com/simplyatul/vagrant-vms/main/kind-install.sh"

end
